import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Divyansh's Portfolio",
  keywords: ["Divyansh", "Portfolio", "Baby Model", "Next.js", "React"],
  authors: [{ name: "Divyansh" }],
  creator: "Anurag",
  openGraph: {
    title: "Divyansh's Portfolio",
    description: "A portfolio showcasing Divyansh's journey as a baby model.",
    url: "https://divyansh-portfolio.vercel.app",
    siteName: "Divyansh's Portfolio",
    images: [
      {
        url: "https://instagram.fdel3-2.fna.fbcdn.net/v/t51.2885-19/522304575_17853231279489077_2617825540006212463_n.jpg?efg=eyJ2ZW5jb2Rl",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path to your favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
          toastOptions={{
            unstyled: true,
            classNames: {
              success:
                "py-2 px-4 flex bg-green-200 text-green-800 gap-2 rounded-lg shadow-md items-center",
              error:
                "py-2 px-4 flex bg-red-200 text-red-800 gap-2 rounded-lg shadow-md items-center",
              info: "py-2 px-4 flex bg-gray-200 text-gray-800 gap-2 rounded-lg shadow-md items-center",
            },
          }}
        />
      </body>
    </html>
  );
}
